//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GmailTest {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Data() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GmailTest.Data", typeof(Data).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Firefox.
        /// </summary>
        internal static string browser {
            get {
                return ResourceManager.GetString("browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на filters.
        /// </summary>
        internal static string filterPage {
            get {
                return ResourceManager.GetString("filterPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 155.120.20.3.
        /// </summary>
        internal static string ipAddress {
            get {
                return ResourceManager.GetString("ipAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vacation responder on.
        /// </summary>
        internal static string messageVocation {
            get {
                return ResourceManager.GetString("messageVocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Material\1.rar.
        /// </summary>
        internal static string nameBigFile {
            get {
                return ResourceManager.GetString("nameBigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на \\log.txt.
        /// </summary>
        internal static string nameLogFile {
            get {
                return ResourceManager.GetString("nameLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Material\свадьба.xlsx.
        /// </summary>
        internal static string nameSmallFile {
            get {
                return ResourceManager.GetString("nameSmallFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на d:\1.rar.
        /// </summary>
        internal static string pathToBigFile {
            get {
                return ResourceManager.GetString("pathToBigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на d:\свадьба.xlsx.
        /// </summary>
        internal static string pathToSmallFile {
            get {
                return ResourceManager.GetString("pathToSmallFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на d:\DSC_8250.jpg.
        /// </summary>
        internal static string pathToSmallFileForCheck {
            get {
                return ResourceManager.GetString("pathToSmallFileForCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на fwdandpop.
        /// </summary>
        internal static string settingPage {
            get {
                return ResourceManager.GetString("settingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на nastya.
        /// </summary>
        internal static string signature {
            get {
                return ResourceManager.GetString("signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на in:spam.
        /// </summary>
        internal static string spamFolder {
            get {
                return ResourceManager.GetString("spamFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vacation responder.
        /// </summary>
        internal static string themVocation {
            get {
                return ResourceManager.GetString("themVocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на emoji.
        /// </summary>
        internal static string topicEmoji {
            get {
                return ResourceManager.GetString("topicEmoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на letter with attech.
        /// </summary>
        internal static string topicLetterWithAttech {
            get {
                return ResourceManager.GetString("topicLetterWithAttech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hi.
        /// </summary>
        internal static string topicLetterWithoutAttech {
            get {
                return ResourceManager.GetString("topicLetterWithoutAttech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на anastasiyaliazhniuk@gmail.com.
        /// </summary>
        internal static string usermail {
            get {
                return ResourceManager.GetString("usermail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на s.lezhnyuk@gmail.com.
        /// </summary>
        internal static string usermail2 {
            get {
                return ResourceManager.GetString("usermail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на nastyakylakova96@gmail.com.
        /// </summary>
        internal static string usermail3 {
            get {
                return ResourceManager.GetString("usermail3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на meniti82.
        /// </summary>
        internal static string userpassword {
            get {
                return ResourceManager.GetString("userpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на m1am1g0s.
        /// </summary>
        internal static string userpassword2 {
            get {
                return ResourceManager.GetString("userpassword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на meniti82.
        /// </summary>
        internal static string userpassword3 {
            get {
                return ResourceManager.GetString("userpassword3", resourceCulture);
            }
        }
    }
}
