//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GmailTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Data() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GmailTest.Data", typeof(Data).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filters.
        /// </summary>
        internal static string filterPage {
            get {
                return ResourceManager.GetString("filterPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 155.120.20.3.
        /// </summary>
        internal static string ipAddress {
            get {
                return ResourceManager.GetString("ipAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation responder on.
        /// </summary>
        internal static string messageVocation {
            get {
                return ResourceManager.GetString("messageVocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d:\1.rar.
        /// </summary>
        internal static string pathToBigFile {
            get {
                return ResourceManager.GetString("pathToBigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d:\свадьба.xlsx.
        /// </summary>
        internal static string pathToSmallFile {
            get {
                return ResourceManager.GetString("pathToSmallFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d:\DSC_8250.jpg.
        /// </summary>
        internal static string pathToSmallFileForCheck {
            get {
                return ResourceManager.GetString("pathToSmallFileForCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fwdandpop.
        /// </summary>
        internal static string settingPage {
            get {
                return ResourceManager.GetString("settingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nastya.
        /// </summary>
        internal static string signature {
            get {
                return ResourceManager.GetString("signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in:spam.
        /// </summary>
        internal static string spamFolder {
            get {
                return ResourceManager.GetString("spamFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation responder.
        /// </summary>
        internal static string themVocation {
            get {
                return ResourceManager.GetString("themVocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to letter with attech.
        /// </summary>
        internal static string topicLetterWithAttech {
            get {
                return ResourceManager.GetString("topicLetterWithAttech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hi.
        /// </summary>
        internal static string topicLetterWithoutAttech {
            get {
                return ResourceManager.GetString("topicLetterWithoutAttech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anastasiyaliazhniuk@gmail.com.
        /// </summary>
        internal static string usermail {
            get {
                return ResourceManager.GetString("usermail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.lezhnyuk@gmail.com.
        /// </summary>
        internal static string usermail2 {
            get {
                return ResourceManager.GetString("usermail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nastyakylakova96@gmail.com.
        /// </summary>
        internal static string usermail3 {
            get {
                return ResourceManager.GetString("usermail3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meniti82.
        /// </summary>
        internal static string userpassword {
            get {
                return ResourceManager.GetString("userpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m1am1g0s.
        /// </summary>
        internal static string userpassword2 {
            get {
                return ResourceManager.GetString("userpassword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meniti82.
        /// </summary>
        internal static string userpassword3 {
            get {
                return ResourceManager.GetString("userpassword3", resourceCulture);
            }
        }
    }
}
